### ISSUE TITLE
Shutters don't open or close fully

### ISSUE THREAD

**Issue by FlyingDan91** [muhlba91/onyx-homeassistant-integration#154]
My automations or even manual control of the shutters via homeassistant don't open or close the shutters fully.
they start to move but they just stop randomly in between and I have to give the command multiple times until they are fully opened or closed. Any ideas?

thank you,
Daniel

**Comment by muhlba91** [comment]
parts of the algorithm to stop the shutters to open/close are related to the data from ONYX about the transition time it calculates. i am adding a small additional delay to it to account for time skews, but in newer versions, a similar problem than you described never occurred.

could you provide the following details:
- which HA & integration version are your running?
- please enable HA debug logging (don't forget to restart) and try to replicate the issue. paste the logs related to the onyx integration (and the specific shutter you tested) here.

**Comment by FlyingDan91** [comment]
Hey,

sure, here are the details:
HA - Core v2024.5.0, SUpervisor V2024.04.4
Integration: Hella Onyx.Center v10.0.0

LOG:
Logger: homeassistant
Quelle: helpers/frame.py:203
Erstmals aufgetreten: 12:14:16 (1 Vorkommnisse)
Zuletzt protokolliert: 12:14:16

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hella_onyx/sensors/shutter.py", line 358, in _end_moving_device
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'hella_onyx' calls async_write_ha_state from a thread at custom_components/hella_onyx/sensors/shutter.py, line 358: self.async_write_ha_state(). Please report it to the author of the 'hella_onyx' custom integration.

Please let me know if this is the correct information. I'm not an expert.

Thanks,
Daniel

**Comment by muhlba91** [comment]
hi,

thank you for these lines. however, there must be some other logs as well if you have set the HA log level to debug. this is now an example for lights but you should see a lot of debug message similar to https://github.com/muhlba91/onyx-homeassistant-integration/issues/89#issuecomment-1852330983.

**Comment by FlyingDan91** [comment]
Sorry for that. 
I activated debug logging now. 
Here the latest log where the issue occurred. 
I have to say also that it was working fine now for like 2 days and now it started again. 

2024-05-10 12:02:56.698 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 29ebcb39-4e54-4878-b6e9-fbdece218946 (Shutter(Device(id=29ebcb39-4e54-4878-b6e9-fbdece218946, name=None, type=None), actual_position=NumericValue(value=88, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=88, minimum=None, maximum=None, animation=None), target_angle=None))
2024-05-10 12:02:56.701 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-05-10 12:02:56.701 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=48, minimum=0, maximum=100, animation=None)
2024-05-10 12:02:56.702 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-05-10 12:02:56.702 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1715335249.2043223, current_value=None, #keyframes=0))
2024-05-10 12:02:56.703 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-05-10 12:02:56.703 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=88, minimum=0, maximum=100, animation=None)
2024-05-10 12:02:56.704 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-05-10 12:04:00.784 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 869bfc45-dba5-4e38-aa9b-c48b6db81ae3 (Shutter(Device(id=869bfc45-dba5-4e38-aa9b-c48b6db81ae3, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1715335440.7438939, current_value=None, #keyframes=0)), actual_angle=None, target_position=None, target_angle=None))
2024-05-10 12:04:00.787 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-05-10 12:04:00.787 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=48, minimum=0, maximum=100, animation=None)
2024-05-10 12:04:00.788 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-05-10 12:04:00.788 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1715335440.7438939, current_value=None, #keyframes=0))
2024-05-10 12:04:00.789 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-05-10 12:04:00.789 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=88, minimum=0, maximum=100, animation=None)

**Comment by muhlba91** [comment]
this is an interesting one because your data is missing keyframe:
`NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1715335249.2043223, current_value=None, #keyframes=0))`

if you check the `#keyframes` they are `0` in your case - this needs to be `> 0` for HA to recognize an intended motion and based on the last keyframe found HA calculates the duration of the motion and when to trigger a `STOP` to force receiving an updated state from ONYX.

however, the keyframes are sent by ONYX and should not affect what you trigger. what i am missing though are lines containing `executing ... for device ...` which are logging what is sent from the integration to ONYX. in you case i'd expect a line similar to `executing OPEN for device <device_id>`.
do you have any other lines in your log file for this integration? 

---

to give you a quick high-level overview of the entire process:
1. you are performing an action (e.g. opening the shutter). this action will be logged in HA with `executing OPEN for device ...` and is directly sent to ONYX. on the HA side, nothing else happens.
2. ONYX triggers the device action and sends an update via its API which contains the requested update. the requested update contains at least an animation with at least one keyframe.
3. HA receives the update (see you log lines), reads the keyframe `duration` and triggers a background wait.
4. if this wait is over, HA triggers a `STOP` action because ONYX will not send an update when the action finished.
5. same as before, `STOP` is executed by ONYX and ONYX sends the updated values.

if ONYX doesn't send a keyframe in an animation, the background wait is not triggered but also no `STOP` is sent. this means that in HA you should see no change but the shutter still moves because ONYX applied the action requested.

**Comment by FlyingDan91** [comment]
Thanks for your response.
Since the update from HA Core to 2024.5.4 it is working properly now. I also can't send any logs since the debugging option was disabled somehow.
But this happened already in the past. So I updated HA Core and then it was working properly. Then with the next update it was failing again. And as i mentioned above with the 5.4 update it is working.
I will update HA Core to the next version at some point and check the logs again.

Greets

**Comment by muhlba91** [comment]
i have fixed the error `RuntimeError: Detected that custom integration 'hella_onyx' calls async_write_ha_state from a thread at custom_components/hella_onyx/sensors/shutter.py, line 358: self.async_write_ha_state(). Please report it to the author of the 'hella_onyx' custom integration.` for now (version `10.1.0`).

i don't think this is going to be root cause of this issue but it would be great if you could test it again and provide new logs with the new release to filter out this error.

**Comment by tKostka** [comment]
Thanks. So far issue still there with 10.1.0. I will activate debug and provide logs, maybe tomorrow or on the weekend.

**Comment by FlyingDan91** [comment]
Hello,

thanks for the update.

Unfortunately the issue still presists.

Here some logs from the latest commands to the shutters via HA:

`2024-07-21 11:46:54.228 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 29ebcb39-4e54-4878-b6e9-fbdece218946 (Shutter(Device(id=29ebcb39-4e54-4878-b6e9-fbdece218946, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0)), actual_angle=None, target_position=None, target_angle=None))
2024-07-21 11:46:54.231 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:46:54.233 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555028.7876232, current_value=None, #keyframes=0))
2024-07-21 11:46:54.234 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:54.235 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555027.3805933, current_value=None, #keyframes=0))
2024-07-21 11:46:54.235 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:54.236 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:46:54.236 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:55.538 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 869bfc45-dba5-4e38-aa9b-c48b6db81ae3 (Shutter(Device(id=869bfc45-dba5-4e38-aa9b-c48b6db81ae3, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0)), actual_angle=None, target_position=None, target_angle=None))
2024-07-21 11:46:55.540 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:46:55.541 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555028.7876232, current_value=None, #keyframes=0))
2024-07-21 11:46:55.542 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:55.542 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:46:55.543 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:55.543 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:46:55.544 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:57.192 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555217.1285915, current_value=None, #keyframes=0)), actual_angle=None, target_position=None, target_angle=None))
2024-07-21 11:46:57.193 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:46:57.195 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555217.1285915, current_value=None, #keyframes=0))
2024-07-21 11:46:57.195 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:57.195 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:46:57.195 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:46:57.196 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:46:57.196 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:01.759 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing {'target_position': 50, 'target_angle': 0} for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:02.204 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555222.1521323, current_value=None, #keyframes=3)), actual_angle=None, target_position=NumericValue(value=50, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:47:02.206 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:47:02.206 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 3e1e9260-7965-46d0-96b4-771df480bf6d: AnimationValue(start=1721555222.1521323, current_value=None, #keyframes=3)
2024-07-21 11:47:02.206 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 3e1e9260-7965-46d0-96b4-771df480bf6d with current_time 1721555222.2067423 < end_time 1721555225.6631322: True
2024-07-21 11:47:02.208 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555222.1521323, current_value=None, #keyframes=3))
2024-07-21 11:47:02.208 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:02.209 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:47:02.210 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:02.210 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:47:02.211 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:05.665 DEBUG (SyncWorker_29) [custom_components.hella_onyx.sensors.shutter] ending moving device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:05.667 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555222.1521323, current_value=None, #keyframes=3))
2024-07-21 11:47:05.668 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:05.671 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:05.893 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=96, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=96, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:47:05.895 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:47:05.897 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=96, minimum=0, maximum=100, animation=None)
2024-07-21 11:47:05.898 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:05.899 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:47:05.899 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:05.900 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:47:05.900 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:55.091 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing {'target_position': 50, 'target_angle': 0} for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:55.464 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=97, minimum=None, maximum=None, animation=AnimationValue(start=1721555275.404657, current_value=97, #keyframes=3)), actual_angle=None, target_position=NumericValue(value=50, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:47:55.466 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:47:55.467 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 3e1e9260-7965-46d0-96b4-771df480bf6d: AnimationValue(start=1721555275.404657, current_value=97, #keyframes=3)
2024-07-21 11:47:55.467 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 3e1e9260-7965-46d0-96b4-771df480bf6d with current_time 1721555275.4676692 < end_time 1721555278.9156568: True
2024-07-21 11:47:55.469 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=97, minimum=0, maximum=100, animation=AnimationValue(start=1721555275.404657, current_value=97, #keyframes=3))
2024-07-21 11:47:55.470 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:55.471 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:47:55.472 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:55.472 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:47:55.473 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:58.918 DEBUG (SyncWorker_25) [custom_components.hella_onyx.sensors.shutter] ending moving device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:58.921 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=97, minimum=0, maximum=100, animation=AnimationValue(start=1721555275.404657, current_value=97, #keyframes=3))
2024-07-21 11:47:58.921 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:58.926 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:47:59.147 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=92, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=92, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:47:59.149 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:47:59.152 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=92, minimum=0, maximum=100, animation=None)
2024-07-21 11:47:59.152 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:59.154 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:47:59.154 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:47:59.155 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:47:59.155 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:03.621 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing open for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:03.750 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=93, minimum=None, maximum=None, animation=AnimationValue(start=1721555283.7152526, current_value=93, #keyframes=3)), actual_angle=None, target_position=NumericValue(value=0, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:48:03.753 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:48:03.753 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 3e1e9260-7965-46d0-96b4-771df480bf6d: AnimationValue(start=1721555283.7152526, current_value=93, #keyframes=3)
2024-07-21 11:48:03.754 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 3e1e9260-7965-46d0-96b4-771df480bf6d with current_time 1721555283.7540116 < end_time 1721555287.2262526: True
2024-07-21 11:48:03.756 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=93, minimum=0, maximum=100, animation=AnimationValue(start=1721555283.7152526, current_value=93, #keyframes=3))
2024-07-21 11:48:03.756 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:03.758 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:48:03.758 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:03.759 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:48:03.760 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:07.227 DEBUG (SyncWorker_1) [custom_components.hella_onyx.sensors.shutter] ending moving device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:07.230 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=93, minimum=0, maximum=100, animation=AnimationValue(start=1721555283.7152526, current_value=93, #keyframes=3))
2024-07-21 11:48:07.231 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:07.235 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:07.439 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=89, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=89, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:48:07.441 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:48:07.443 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=89, minimum=0, maximum=100, animation=None)
2024-07-21 11:48:07.443 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:07.445 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:48:07.445 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:07.446 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:48:07.447 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:13.713 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing {'target_position': 20, 'target_angle': 0} for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:13.870 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555293.8101487, current_value=89, #keyframes=3)), actual_angle=None, target_position=NumericValue(value=20, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:48:13.872 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:48:13.873 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 3e1e9260-7965-46d0-96b4-771df480bf6d: AnimationValue(start=1721555293.8101487, current_value=89, #keyframes=3)
2024-07-21 11:48:13.873 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 3e1e9260-7965-46d0-96b4-771df480bf6d with current_time 1721555293.8736253 < end_time 1721555297.3211486: True
2024-07-21 11:48:13.878 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=89, minimum=0, maximum=100, animation=AnimationValue(start=1721555293.8101487, current_value=89, #keyframes=3))
2024-07-21 11:48:13.878 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:13.880 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:48:13.880 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:13.881 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:48:13.881 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:17.323 DEBUG (SyncWorker_41) [custom_components.hella_onyx.sensors.shutter] ending moving device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:17.325 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:17.330 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=89, minimum=0, maximum=100, animation=AnimationValue(start=1721555293.8101487, current_value=89, #keyframes=3))
2024-07-21 11:48:17.331 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:17.584 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=85, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=85, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:48:17.585 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:48:17.586 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=85, minimum=0, maximum=100, animation=None)
2024-07-21 11:48:17.587 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:17.587 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:48:17.588 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:17.588 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:48:17.588 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:51.859 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing close for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:48:52.189 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1721555332.1322675, current_value=85, #keyframes=1)), actual_angle=None, target_position=NumericValue(value=100, minimum=None, maximum=None, animation=None), target_angle=None))
2024-07-21 11:48:52.191 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:48:52.192 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 3e1e9260-7965-46d0-96b4-771df480bf6d: AnimationValue(start=1721555332.1322675, current_value=85, #keyframes=1)
2024-07-21 11:48:52.192 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 3e1e9260-7965-46d0-96b4-771df480bf6d with current_time 1721555332.192512 < end_time 1721555345.8252676: True
2024-07-21 11:48:52.194 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=85, minimum=0, maximum=100, animation=AnimationValue(start=1721555332.1322675, current_value=85, #keyframes=1))
2024-07-21 11:48:52.195 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:52.196 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:48:52.197 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:48:52.198 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:48:52.198 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:49:05.826 DEBUG (SyncWorker_31) [custom_components.hella_onyx.sensors.shutter] ending moving device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:49:05.829 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=85, minimum=0, maximum=100, animation=AnimationValue(start=1721555332.1322675, current_value=85, #keyframes=1))
2024-07-21 11:49:05.829 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:49:05.833 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 3e1e9260-7965-46d0-96b4-771df480bf6d
2024-07-21 11:49:06.015 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 3e1e9260-7965-46d0-96b4-771df480bf6d (Shutter(Device(id=3e1e9260-7965-46d0-96b4-771df480bf6d, name=None, type=None), actual_position=NumericValue(value=100, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=None, target_angle=None))
2024-07-21 11:49:06.017 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-07-21 11:49:06.019 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=100, minimum=0, maximum=100, animation=None)
2024-07-21 11:49:06.020 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 3e1e9260-7965-46d0-96b4-771df480bf6d: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:49:06.021 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=100, animation=AnimationValue(start=1721555215.473834, current_value=None, #keyframes=0))
2024-07-21 11:49:06.021 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 869bfc45-dba5-4e38-aa9b-c48b6db81ae3: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-07-21 11:49:06.023 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1721555214.1884224, current_value=None, #keyframes=0))
2024-07-21 11:49:06.023 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 29ebcb39-4e54-4878-b6e9-fbdece218946: NumericValue(value=0, minimum=0, maximum=360, animation=None)`

**Comment by muhlba91** [comment]
sorry for the silence. i finally found some time to look at your debug logs, and i believe the reason was that you had multiple keyframes in your movement command.
until now, on my side, i always had only a single one, which explains why it didn't happen to my setup.

i have published `10.2.1`, which includes a fix to sum up all keyframe durations and delays to calculate the current state. this is not perfect when interpolation happens because interpolation should consider that delays can be distributed; however, i don't believe that the delays would add up so much to have a visible effect on it.

could you please try the new version and provide feedback on this issue?

**Comment by tKostka** [comment]
Thanks a lot, it seems to be fixed or at least nearly.  I opened my shutter about 7 times with the new version, only 1 time it was not opened to 100%. I couldn't reproduce it since i activated debug logging. I will provide logs if it happens again. 
With the previous version it was opening to about 80-90% everytime with my morning automation.

**Comment by muhlba91** [comment]
thank you for the feedback!

if this happens again, please also let me know if this was off by quite some percent or just a few milliseconds until the shutter state had been reached. (see #220 as i am thinking about whether some timing issues could cause an early stop)

**Comment by tKostka** [comment]
That helped to understand the log entries, thanks. In my case 1 or 2 more seconds would help. See logs from today, it stopped at position 9.

``` 2024-10-21 09:38:09.535 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: AnimationValue(start=1729496289.5034049, current_value=100, #keyframes=1)
2024-10-21 09:38:09.535 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] not moving still device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c
2024-10-21 09:38:09.536 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1729496289.5034049, current_value=100, #keyframes=1))
2024-10-21 09:38:09.542 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1729496289.5034049, current_value=100, #keyframes=1)), actual_angle=None, target_position=None, target_angle=None))
2024-10-21 09:38:09.545 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:39:45.155 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing {'target_position': 0, 'target_angle': 0} for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c
2024-10-21 09:39:45.382 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1729496385.3467283, current_value=None, #keyframes=1)), actual_angle=None, target_position=NumericValue(value=0, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:39:45.384 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:39:45.391 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=None, minimum=None, maximum=None, animation=AnimationValue(start=1729496385.3467283, current_value=None, #keyframes=1)), actual_angle=None, target_position=NumericValue(value=0, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:39:45.393 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:39:45.394 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position_animation for shutter 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: AnimationValue(start=1729496385.3467283, current_value=None, #keyframes=1)
2024-10-21 09:39:45.394 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] moving device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c with current_time 1729496385.3945787 < end_time 1729496411.7547283: True
2024-10-21 09:39:45.396 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1729496385.3467283, current_value=None, #keyframes=1))
2024-10-21 09:39:45.397 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-10-21 09:40:11.756 DEBUG (SyncWorker_2) [custom_components.hella_onyx.sensors.shutter] ending moving device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c
2024-10-21 09:40:11.757 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=100, minimum=0, maximum=100, animation=AnimationValue(start=1729496385.3467283, current_value=None, #keyframes=1))
2024-10-21 09:40:11.757 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-10-21 09:40:11.761 INFO (MainThread) [custom_components.hella_onyx.api_connector] executing stop for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c
2024-10-21 09:40:11.922 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=8, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=8, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:40:11.925 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:40:11.932 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=8, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=8, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:40:11.935 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:40:11.937 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=8, minimum=0, maximum=100, animation=None)
2024-10-21 09:40:11.937 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-10-21 09:41:40.643 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=9, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=9, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:41:40.645 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:41:40.646 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=9, minimum=0, maximum=100, animation=None)
2024-10-21 09:41:40.646 DEBUG (MainThread) [custom_components.hella_onyx.sensors.shutter] received tilt position for device 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c: NumericValue(value=0, minimum=0, maximum=360, animation=None)
2024-10-21 09:41:40.661 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] received device update 8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c (Shutter(Device(id=8xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx103c, name=None, type=None), actual_position=NumericValue(value=9, minimum=None, maximum=None, animation=None), actual_angle=None, target_position=NumericValue(value=9, minimum=None, maximum=None, animation=None), target_angle=None))
2024-10-21 09:41:40.663 DEBUG (MainThread) [custom_components.hella_onyx.api_connector] Manually updated hella_onyx data
2024-10-21 09:51:40.643 WARNING (MainThread) [custom_components.hella_onyx.api_connector] connection reset: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>, restarting with backoff of 3 seconds (True)
2024-10-21 09:51:40.653 WARNING (MainThread) [custom_components.hella_onyx.api_connector] connection reset: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>, restarting with backoff of 51 seconds (True)
```

**Comment by muhlba91** [comment]
`v10.3.0` introduces a new option (under Settings > Devices & Services > Hella ONYX.CENTER > Configure) called "Additional Delay for forced STOP". I increased it to 1s by default for now. let me know if this fixes the problem now.

btw, the `connection reset` error is known under #30 and once Hella released the v2.9 it apparently should be fixed. according to https://github.com/hella-info/onyx_api/issues/9 the release is targeted for this year but no hard confirmation.

**Comment by tKostka** [comment]
Great, for me it is working perfectly now. Thank you very much.

**Comment by FlyingDan91** [comment]
Hello all,

i tested now since a couple of days and its working perfectly fine now.

Thank you very much!

**Comment by muhlba91** [comment]
awesome, and sorry for the late attention to this bug. i'm going to close it - please re-open it if necessary.
